cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path
from .views import *

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<int:category_id>', product_list, name='select_category'),
    path('<int:id>/', product_detail, name='product_detail')]

orders/urls.py
from django.urls import path

from .views import order

app_name = 'orders'

urlpatterns = [
    path('', order, name='order')
]

store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('cart', include('cart.urls')),
    path('orders', include('orders.urls'))

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='', choices=[(i, str(i)) for i in range(1, 21)],
                                      coerce=int,
                                      widget=forms.Select(
                                          attrs={'class': 'form-control'}
                                      ))

    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages

from .cart import Cart
from .forms import CartAddProductForm
from catalog.models import Product


@require_POST
def cart_add (request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product=product, quantity=form.cleaned_data['quantity'], update_quantity=form.cleaned_data['update'])
    return redirect('cart:cart_detail')


def cart_remove (request, product_id):
    cart = Cart(request)
    cart.remove(str(product_id))
    messages.success(request, 'Удалено')
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%; ">
        <h2>
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        Текущий список покупок:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, {{ cart.get_total_price }}
                        </a>
                        {% else %}
                       Корзина пуста
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
        <table class="table table-dark table-hover" style="background: #212529;">
            <thead>
              <tr>
                <th scope="col">Изображение</th>
                <th scope="col">Товар</th>
                <th scope="col">Кол-во</th>
                <th scope="col">Удалить</th>
                <th scope="col">Цена одного товара</th>
                <th scope="col">Цена</th>
              </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <th scope="row">
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            </th>
                            <td>{{ product.title }}</td>
                            <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                <span style="display:inline-block">
                                    <div class="col-auto">
                                        {{ item.update_quantity_form.quantity}}
                                        {{ item.update_quantity_form.update }}
                                    </div>
                                    <input type="submit" value="Изменить" class="btn btn-outline-info" style="margin-top:10%;">
                                </span>
                            </form>
                            </td>
                            <td>
                                <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                            </td>
                            <td> {{ item.quantity }}</td>
                            <td> {{ item.total_price }}</td>

                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td><b>Суммарная стоимость</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b> {{ cart.get_total_price }}</b></td>
                </tr>
            </tbody>
          </table>

                </tbody>
            </table>


            <p class="text-right">
                <a href="{% url 'catalog:product_list' %}" class="btn btn-dark" style="background: #212529;"><p3 style ='color:white'>Продолжить покупку</p3></a>
                {% if cart|length > 0 %}
                    <a href="{% url 'orders:order'%}" class="btn btn-dark" style="background: #212529;"><p3 style ='color:white'>Оформить заказ</p3></a>
                {%endif%}
            </p>

        </div>
    </div>
{% endblock %}