cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('cart', include('cart.urls')),
    path('orders', include('orders.urls'))

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Site</title>
    <style>
        .container-my {
            background: #212529;
            max-width: 400px;
            height: 510px;
            position: relative;
            margin-top: 10%;
            margin-left: auto;
            margin-right: auto;
            padding-right: 15px;
            padding-left: 15px;
            border-radius: 40px;
        }
        #logo{background: white}
        #mynav{background: #212529;}

        #store { margin-left: 500px; }
                   @media screen and (max-width: 1700px) {
                     #store { margin-left: 390px; }

                     @media screen and (max-width: 1650px) {
                     #store { margin-left: 300px; }

                     @media screen and (max-width: 1500px) {

                     #store { margin-left: 250px; }

                     @media screen and (max-width: 1300px) {
                     #store { margin-left: 200px; }

                     @media screen and (max-width: 1150px) {
                     #store { margin-left: 150px; }

                     @media screen and (max-width: 1020px) {
                     #store { margin-left: 100px; }

                     @media screen and (max-width: 955px) {
                     #store { margin-left: 70px; }

                     @media screen and (max-width: 850px) {
                     #store { margin-left: 50px; }

                     @media screen and (max-width: 820px) {
                     #store { margin-left: 45px; }
                   }}}}}}}}}

    </style>
</head>
<body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" id="mynav">
            <a class="navbar-brand" href="#">
               <img alt="Brand" class="img-responsive" id="logo" width=160rem height=auto src="media/navbar_image/hsbc-logo-black-and-white.png">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">


                <li class="nav-item" >
                    {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                            <svg class="bi bi-cart-fill" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                 <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                            </svg>
                            <span class="badge badge-secondary">{{ totail_items }}</span>
                        </a>
                    {% else %}
                        <a class="nav-link" href="">
                          <svg class="bi bi-cart" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                          </svg>
                        </a>
                    {% endif %}
                {% endwith %}
            </li>

              </ul>
                <div class="nav navbar-nav navbar-right">
                  <div class="nav-item">
                      <a class="btn btn-warning " href="/admin">Вход</a>
                  </div>
                </div>
            </div>

        </nav>
      {%block content%}


      {%endblock%}




    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

   <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
           integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!-- jQuery -->
   <script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Popper -->
   <script src="/examples/vendors/popper.js/popper.min.js"></script>
<!-- Bootstrap JS -->
   <script src="/examples/vendors/bootstrap-4/js/bootstrap.min.js"></script>

</body>
</html>